start chrome "Z:\Site Visit Conversions\A02 West\917 - Fresno County, CA\3 - Peer Review\DIV_917_High_Priority_Accounts.html"
start chrome "Z:\Site Visit Conversions\A02 West\917 - Fresno County, CA\3 - Peer Review\DIV_917_MUNI_Atwater_CA.html"
start chrome "Z:\Site Visit Conversions\A02 West\917 - Fresno County, CA\3 - Peer Review\DIV_917_MUNI_City_of_Fresno_Commercial_Pricing_Zone_1_City_of_Fresno_CA.html"
start chrome "Z:\Site Visit Conversions\A02 West\917 - Fresno County, CA\3 - Peer Review\DIV_917_MUNI_Clovis_CA.html"
start chrome "Z:\Site Visit Conversions\A02 West\917 - Fresno County, CA\3 - Peer Review\DIV_917_MUNI_Clovis_Commercial_Pricing_Recycle_Clovis_CA.html"
start chrome "Z:\Site Visit Conversions\A02 West\917 - Fresno County, CA\3 - Peer Review\DIV_917_Temp_Container_Information.html"
